#! /bin/bash

# modified version of file from http://websvn.kde.org/trunk/l10n-kde4/scripts/extract-messages.sh

podir="${PWD}"/po
srcdir="${PWD}"
dirs="krusader krArc tar iso"
EXTRACTRC="${EXTRACTRC:-${PWD}/extractrc}"
EXTRACTATTR=${EXTRACTATTR:-extractattr}
PREPARETIPS=${PREPARETIPS:-preparetips}
export EXTRACTRC EXTRACTATTR PREPARETIPS
XGETTEXT_FLAGS="--copyright-holder=This_file_is_part_of_the_Krusader --from-code=UTF-8 -C --kde -ci18n -ki18n -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 -ktr2i18n:1 -kI18N_NOOP:1 -kI18N_NOOP2:1c,2 -kaliasLocale -kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 --flag=i18n:1:kde-format --flag=i18nc:2:kde-format --flag=i18np:2:kde-format --flag=i18ncp:3:kde-format  --msgid-bugs-address=krusader-i18n@googlegroups.com"
export XGETTEXT_FLAGS

> ${podir}/krusader.pot 

for subdir in $dirs; do
  echo "Making messages in $subdir"
  (
    cd $srcdir/$subdir
    find . -name .svn -prune -o -regex '.*[.]\(rc\|ui[34]?\|kcfg\)' -print 2> /dev/null | xargs --no-run-if-empty $EXTRACTRC > rc.cpp
    files=$
    if find . -name \*.c\* -o -name \*.h\* | fgrep -v ".svn" | xargs fgrep -s -q KAboutData
    then
      echo 'i18nc("NAME OF TRANSLATORS","Your names");' >> rc.cpp
      echo 'i18nc("EMAIL OF TRANSLATORS","Your emails");' >> rc.cpp
    fi
  )

  for i in $srcdir/$subdir
  do
    test -d $i || continue
    cd $i
    find . -name \*.c\* -o -name \*.h\* | fgrep -v ".svn" \
    | xargs "${XGETTEXT:-xgettext}" $XGETTEXT_FLAGS -j -o ${podir}/krusader.pot 
    exit_code=$?
    if test "$exit_code" -ne 0; then
      echo "Bash exit code: $exit_code"
    else
      true
      rm -f rc.cpp
    fi
  done
done 2>&1

